apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: microservices-monitor
  namespace: monitoring
  labels:
    release: monitoring # Matches the name of your Helm install
spec:
  selector:
    matchLabels:
      monitoring: "enabled" # Tells Prometheus to look for this label
  endpoints:
    - port: web # Matches the port name in your Service
      path: /metrics
      interval: 15s
