name: Build and Push Images

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and Push Orders Service
      - name: Build Orders Image
        uses: docker/build-push-action@v5
        with:
          context: ./orders-service # Adjust to your folder name
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/orders-service:latest

      # Build and Push Inventory Service
      - name: Build Inventory Image
        uses: docker/build-push-action@v5
        with:
          context: ./inventory-service # Adjust to your folder name
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/inventory-service:latest
